name: contex variable

on: workflow_dispatch
env:
    cloud: AWS

jobs: 
  greetings_job: 
    runs-on: ubuntu-latest
    steps:
      - name: myfirstcard
        run: echo "Hello world ${{ github.actor }} is expert in $cloud"
     
   
    
  
    

 
