name: myownflow

on: push

env: 
  cloud: google-cloud
jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      greeting: Hello
    steps: 
      - name: "Say hello Najish its Monday"
        run: echo "$greeting $firstname is using $cloud with project ${{vars.project_ID}}"
        env:
         firstname: Najish
